# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

a = Analysis(
    ['pyinstaller_entry.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('backend/security', 'backend/security'),
    ],
    hiddenimports=[
        # --- Uvicorn / FastAPI / Starlette ---
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'fastapi',
        'pydantic',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.responses',
        'starlette.requests',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'httptools',
        # --- OpenAI SDK ---
        'openai',
        'openai.resources',
        'openai.resources.chat',
        'openai.resources.chat.completions',
        'openai._streaming',
        'openai._base_client',
        'openai._client',
        'httpx',
        'httpx._transports',
        'httpx._transports.default',
        'httpcore',
        'httpcore._async',
        'httpcore._sync',
        'h11',
        'h2',
        'hpack',
        'hyperframe',
        'socksio',
        'sniffio',
        'distro',
        'jiter',
        # --- Anthropic SDK ---
        'anthropic',
        'anthropic.resources',
        'anthropic.resources.messages',
        'anthropic._streaming',
        'anthropic._base_client',
        'anthropic._client',
        'tokenizers',
        # --- Google Generative AI SDK ---
        'google',
        'google.generativeai',
        'google.generativeai.types',
        'google.generativeai.client',
        'google.api_core',
        'google.api_core.exceptions',
        'google.api_core.gapic_v1',
        'google.auth',
        'google.auth.transport',
        'google.auth.transport.requests',
        'google.protobuf',
        'google.protobuf.json_format',
        'proto',
        'proto.marshal',
        'proto.marshal.rules',
        'grpc',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PIL', 'Pillow', 'matplotlib', 'scipy', 'IPython',
        'notebook', 'pytest', 'tkinter', 'test',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='main',
)
